// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0RZ_Saj8aiZK1ugaLYI0stncyjT65tVE',
    appId: '1:880450340552:web:2db83a994f14d64a8a87fd',
    messagingSenderId: '880450340552',
    projectId: 'farmer-9ac0d',
    authDomain: 'farmer-9ac0d.firebaseapp.com',
    storageBucket: 'farmer-9ac0d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMrqTeaOE1Iiaiuw7P8T6hdVboQvUZ1V4',
    appId: '1:880450340552:android:a8a600afa417d78a8a87fd',
    messagingSenderId: '880450340552',
    projectId: 'farmer-9ac0d',
    storageBucket: 'farmer-9ac0d.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDye8WaQmDkfcV0zn1CdRBf6CWzxV_mvoE',
    appId: '1:880450340552:ios:daaa5f16a8f7d4548a87fd',
    messagingSenderId: '880450340552',
    projectId: 'farmer-9ac0d',
    storageBucket: 'farmer-9ac0d.appspot.com',
    iosBundleId: 'com.example.farmer.RunnerTests',
  );
}
